# Form implementation generated from reading ui file 'gui_vote.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 350)
        MainWindow.setMinimumSize(QtCore.QSize(300, 350))
        MainWindow.setMaximumSize(QtCore.QSize(300, 350))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_voter_id = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_voter_id.setObjectName("label_voter_id")
        self.horizontalLayout.addWidget(self.label_voter_id)
        self.input_voter_id = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_voter_id.setObjectName("input_voter_id")
        self.horizontalLayout.addWidget(self.input_voter_id)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_candidates = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_candidates.setObjectName("label_candidates")
        self.verticalLayout.addWidget(self.label_candidates)
        self.button_jane = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.button_jane.setObjectName("button_jane")
        self.verticalLayout.addWidget(self.button_jane)
        self.button_john = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.button_john.setObjectName("button_john")
        self.verticalLayout.addWidget(self.button_john)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label_validation = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_validation.setObjectName("label_validation")
        self.verticalLayout_2.addWidget(self.label_validation)
        self.button_submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_submit.setObjectName("button_submit")
        self.verticalLayout_2.addWidget(self.button_submit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GUI Voting App"))
        self.label_voter_id.setText(_translate("MainWindow", "ID:"))
        self.label_candidates.setText(_translate("MainWindow", "CANDIDATES"))
        self.button_jane.setText(_translate("MainWindow", "Jane"))
        self.button_john.setText(_translate("MainWindow", "John"))
        self.label_validation.setText(_translate("MainWindow", "Confirm your vote"))
        self.button_submit.setText(_translate("MainWindow", "SUBMIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
